BIN  := ./$(LEVEL)/bin

SRCS := $(wildcard *.cpp) $(wildcard */*.cpp)
ifdef KERNEL
	SRCS += ./$(LEVEL)/$(KERNEL)
endif
OBJS := $(patsubst %.cpp, %.o, $(SRCS))

CPPFLAGS += 
CXXFLAGS += -g -Wall -std=c++11

all: $(TARGET)

$(OBJS): %.o: %.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c -o $@ $<

$(TARGET): $(OBJS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -o $@ $(OBJS)

install:
	cp $(TARGET) $(OTHER_TARGET) $(BIN)/

clean :
	rm -f $(OBJS) $(TARGET)

